#!/bin/bash
# EC2 admin

#environment variables for EC2
export EC2_PRIVATE_KEY=$EC2_HOME/pk-QVNJPBQNTDJ3GEJWZNHIZHHFBMJVUT4J.pem 
export EC2_CERT=$EC2_HOME/cert-QVNJPBQNTDJ3GEJWZNHIZHHFBMJVUT4J.pem

#Get data volume description
#DV=$(ec2-describe-volumes -F tag:Name='Data Volume')
vid=vol-e5948f91
bktime=$(date +"%c")

echo $vid
echo $bktime

#create snapshot
ec2-create-snapshot $vid -d "Backup: $bktime"

#delete oldest


